apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
spec:
    selector:
        matchLabels:
            app: postgres
    replicas: 1
    template:
        metadata:   
            labels:
                app: postgres
        spec:
            containers:
            - name: postgres 
              image: postgres:11.7-alpine
              ports:
               - containerPort: 5432
                 name: postgres
              envFrom:
               - configMapRef:
                    name: postgres-config
              volumeMounts:
               - mountPath: /var/lib/postgresql/data
                 name: postgres-storage
            volumes:
             - name: postgres-storage
               persistentVolumeClaim:
                     claimName: postgres-pv-claim
                 